# Generated by Django 3.2.9 on 2021-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zip',
            field=models.SmallIntegerField(null=True),
        ),
    ]
